###############################################################################
# Stage -- Quality Assurance
###############################################################################

.quality-setup:
  extends: .tox-setup
  stage: quality
  before_script:
    - !reference [.tox-setup, before_script]

pre-commit:
  extends: .quality-setup
  script:
    - tox -e pre-commit
