###############################################################################
# Stage -- Security Scanning
###############################################################################
#
# Overrides:
#
# 1) Installed "tools" and "example_deps" extras
#
###############################################################################

dependency_scanning:
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only main,linting,tests,docs --extras "tools example_deps"
