###############################################################################
# Stage -- Unit Testing
###############################################################################
#
# Overrides:
#
# 1) Installed "tools" and "example_deps" extras
# 2) xaitk-saliency specific notebooks.
#
###############################################################################

notebooks:
  extends: .notebooks
  rules: !reference [.notebooks, rules]
  variables:
    EXTRAS: "tools example_deps"
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "docs/examples"
        NOTEBOOK_FILE: [
          "atari_deepRL_saliency.ipynb",
          "DRISE.ipynb",
          "MC_RISE.ipynb",
          "MNIST_scikit_saliency.ipynb",
          "OcclusionSaliency.ipynb",
          "Radial_Image_Perturbation.ipynb",
          "SimilarityScoring.ipynb",
          "SuperPixelSaliency.ipynb",
          "SwappableImplementations.ipynb",
          # VIAME notebook takes longer than 60 minutes to execute (timeout limit)
          #"VIAME_OcclusionSaliency.ipynb",
          # # Shared memory issue on GitLab
          "SerializedDetectionSaliency.ipynb",
          # Model comparison example is excluded due to computational complexity
          #"ModelComparisonWithSaliency.ipynb",
        ]

pytest-extras:
  allow_failure: false
  variables:
    EXTRAS: "tools example_deps"

# This is a temporary override while we wait for devel-jatic to support 3.13
.python-versions:
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.10", "3.11", "3.12", "3.13" ]
