name: Publish

# Controls when the action will run.
on:
  push:
    tags:
      # Only run on tags with official version tag release format (e.g. v1.0.1)
      - "v[0-9].[0-9]+.[0-9]+"

  # Allow use of this workflow as a reusable workflow.
  # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    # This should only be run for tags on the "official" repository org.
    if: github.repository_owner == 'XAITK'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          pip install --root-user-action=ignore --only-binary :all: --user -U "poetry==2.4.3" -q
          poetry --version
          poetry check

      # Ensure there is alignment with the tag reference and the reported
      # version of the package
      - name: Ensure synchronized pacakge and ref
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          PACKAGE_VERSION="v$(poetry version -s)"
          if [[ "$REF_NAME" != "${PACKAGE_VERSION}" ]]
          then
            echo "ERROR: Git tag reference and package version are NOT synonymous."
            echo "       Package version: ${PACKAGE_VERSION}"
            echo "       Git ref name   : ${REF_NAME}"
            exit 1
          fi

      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN}}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ -z "$POETRY_PYPI_TOKEN_PYPI" ]]
          then
            echo "ERROR: Input pypi token was blank. Did you forget to set the appropriate secret?"
            exit 1
          fi
          echo "Publishing new tag: ${REF_NAME}"
          poetry publish --build
